/**
 * @file peripheral_mapping.cpp
 * @author Javnson (javnson@zju.edu.cn)
 * @brief 
 * @version 0.1
 * @date 2024-09-30
 * 
 * @copyright Copyright GMP(c) 2024
 * 
 */

// This file's framework is generated by bsp_c1
#include <core/gmp_core.hpp>
#include <ctl/ctrl_config.h>



//////////////////////////////////////////////////////////////////////////
// Peripherals implement classes



//////////////////////////////////////////////////////////////////////////
// Devices on the peripheral


// This function should be implement by bsp_c1
void gmp_init_peripheral_tree()
{
	uart.init();

	// enable debug port
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
	default_debug_dev = &uart;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC


}

//////////////////////////////////////////////////////////////////////////
// interrupt reaction



