

// This file's framework is generated by bsp_c1
#include <core/std/typedef.h>
#include <bsp/user/peripheral_mapping.h>
#include <core/mm/mem.h>
#include <core/util/dbg_prt/dbg_prt.h>
#include <core/dev/io_functions.h>
#include <core/util/ds/data_ring_buffer.h>
#include <core/std/global.h>

gmp_peripheral_t gmp_iic1 = GMP_IIC_1;
gmp_iic_mapping_t gmp_iic_bh1750 = GMP_IIC_BH1750;
gmp_iic_mapping_t gmp_iic_bmp180 = GMP_IIC_BMP180;

gmp_peripheral_t gmp_uart_dbg = GMP_UART_DBG;
gmp_phy_mapping_t gmp_uart_dbg_port = GMP_UART_DBG_PORT;


void gmp_setup_peripheral()
{
	// DSP standard setup process

	// Step 1. Initialize System Control registers, PLL, WatchDog, Clocks to 
	// default state: This function is found in the F2806x_SysCtrl.c file.
	InitSysCtrl();

	InitSciGpio();

	// Step 2. clear all CPU interrupts
	DINT;
	IER = 0x0000;
	IFR = 0x0000;
	InitPieVectTable();
	EnableInterrupts();

	// Step 3. Setup peripheral
	SCI_init(&gmp_uart_dbg_port);

	
	// Finally, GMP peripheral config
	default_dbg_hdev = (gmp_phy_mapping_t*)&gmp_uart_dbg_port;

	// IIC1 
	//init_ring_buffer(gmp_iic1.rx_buf);

	// IIC2 receive buffer
	init_ring_buffer((gmp_ring_buffer_t**)&gmp_uart_dbg.rx_buf,
		GMP_DEFAULT_BUFFER_SIZE);
}


// This function should be implement by bsp_c1
void gmp_init_peripheral_tree()
{


}

//////////////////////////////////////////////////////////////////////////
// interrupt reaction


//void HAL_UART_RxCpltCallback(UART_HandleTypeDef* huart)
//{
//	gmp_param_t timeout = 0;
//
//	gmp_data_t rx_buffer;
//
//	// Check UART state
//	while (HAL_UART_GetState(&huart1) != HAL_UART_STATE_READY)
//		if (timeout++ > TIMEOUT_CNT)
//			return;
//
//	// Check Receive buffer
//	timeout = 0;
//	while (HAL_UART_Receive_IT(&huart1, &rx_buffer, 1) != HAL_OK)
//		if (timeout++ > TIMEOUT_CNT)
//			return;
//
//	// tell GMP the received message
//	gmp_port_recv_int_response(
//		&gmp_uart_dbg,
//		&rx_buffer, 1,
//		0
//	);
//
//	return;
//}
