

// This file's framework is generated by bsp_c1
#include <core/gmp_core.hpp>
#include <ctl/ctl.config.h>



//////////////////////////////////////////////////////////////////////////
// Peripherals implement classes
//gmp_uart_stm32_impl_t dbg_uart(&huart1);


//////////////////////////////////////////////////////////////////////////
// Devices on the peripheral

void gmp_setup_peripheral()
{


}

// This function should be implement by bsp_c1
void gmp_init_peripheral_tree()
{


}

//////////////////////////////////////////////////////////////////////////
// interrupt reaction



