

// This file's framework is generated by bsp_c1

#include "peripheral_mapping.h"


gmp_iic_mapping_t gmp_iic_bh1750 = GMP_IIC_BH1750;
gmp_iic_mapping_t gmp_iic_bmp180 = GMP_IIC_BMP180;
gmp_peripheral_t gmp_iic1 = GMP_IIC_1;


 