//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.


// standard typedef
#include <core/std/typedef.h>

#include <csp/chip_support_selection.h>

#include <core/dev/prototypes.h>

#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

	//////////////////////////////////////////////////////////////////////////
	// Handle Type definition

//	extern ADC_HandleTypeDef hadc1;
//	extern DMA_HandleTypeDef hdma_adc1;
//	extern I2C_HandleTypeDef hi2c1;
//	extern I2C_HandleTypeDef hi2c2;
//	extern RTC_HandleTypeDef hrtc;
//	extern SPI_HandleTypeDef hspi2;
//	extern UART_HandleTypeDef huart1;
//	extern UART_HandleTypeDef huart2;


	//////////////////////////////////////////////////////////////////////////
	// Peripheral Variables
	extern gmp_peripheral_t gmp_iic1; // gmp_<peripheral_name>_hdev
	extern gmp_iic_mapping_t gmp_iic_bh1750;
	extern gmp_iic_mapping_t gmp_iic_bmp180;

	//////////////////////////////////////////////////////////////////////////
	// Peripheral Macros
#define GMP_IIC_1 {PROTO_PERIPHERAL_IIC, 10, NULL, 0,0,0,0,0,0,0,0}


	//////////////////////////////////////////////////////////////////////////
	// Peripheral Mappings
#define GMP_IIC_BH1750 {&gmp_iic1, 0b0100011}
#define GMP_IIC_BMP180 {&gmp_iic1, 0b1110111}


	//////////////////////////////////////////////////////////////////////////
	// function
#ifdef __cplusplus
	extern "C"
	{
#endif

		// User should implement this two functions 
		void user_init(void);
		void user_loop(void);


#ifdef __cplusplus
	}
#endif

#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_