

// This file's framework is generated by bsp_c1
#include <core/gmp_core.hpp>
#include <ctl/ctl.config.h>


#include <user_main.hpp>

#include <ctl/suite/pmsm/pmsm_speed_closeloop/pmsm_speed_closeloop.h>

//////////////////////////////////////////////////////////////////////////
// Peripherals implement classes
//gmp_uart_stm32_impl_t dbg_uart(&huart1);

extern TIM_HandleTypeDef htim1;
extern pmsm_ctl_object_t pmsm;



//////////////////////////////////////////////////////////////////////////
// Devices on the peripheral

void gmp_setup_peripheral()
{
//	// start DMA first
//	HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_data, 6);

//	// Enable HRTIM
//	HAL_HRTIM_WaveformCounterStart(&hhrtim1,
//		HRTIM_TIMERID_MASTER | HRTIM_TIMERID_TIMER_A | HRTIM_TIMERID_TIMER_B);

//	// Enable TIM16 for CPU usage counter
//	HAL_TIM_Base_Start(&htim16);


	// ADC enable
	//__HAL_ADC_ENABLE_IT(&hadc1, ADC_IT_EOS);
}

// This function should be implement by bsp_c1
void gmp_init_peripheral_tree()
{
	// enable debug port
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
//	default_debug_dev = &dbg_uart;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC


}

//////////////////////////////////////////////////////////////////////////
// interrupt reaction


// ADC Complete callback
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
	uint32_t cpu_usage = __HAL_TIM_GET_COUNTER(&htim1);
	
    ctl_dispatch();
	
	uint32_t cpu_usage2 = __HAL_TIM_GET_COUNTER(&htim1);
	
	pmsm.base.control_law_CPU_usage_tick = cpu_usage2 - cpu_usage;
}
