//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.


#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

	//////////////////////////////////////////////////////////////////////////
	// Handle Type definition, copy from <main.c>
	// 
	// 
	
#ifndef SPECIFY_PC_TEST_ENV



#endif // SPECIFY_PC_TEST_ENV


	//////////////////////////////////////////////////////////////////////////
	// Peripheral Variables
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
// This is the default debug device handle
extern dbgptr_gt default_debug_dev;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC

	extern uint16_t adc_data[6];

//extern gmp_iic_stm32_impl_t iic;
//extern gmp_uart_stm32_impl_t dbg_uart;
//extern gmp_pwm1ch_stm32_impl_t pwm_ch1;

	//////////////////////////////////////////////////////////////////////////
	// Devices on the peripheral


	//////////////////////////////////////////////////////////////////////////
	// function


	// User should implement this two functions at least
	void user_init(void);
	void user_loop(void);

	//////////////////////////////////////////////////////////////////////////
	// Additionally functions



#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_
