// This file's framework is generated by bsp_c1

#include "../bsp_header.h"

gmp_peripheral_t* gmp_iic1_hdev;

// This function should be called in `main` initialize routine.
// This function should implement by user to setup all the peripherals of the chip.
void _peripheral_setup( void )
{
	// init peripheral
	// Cube MX completed.
	bsp_setup_peripheral();

	// init peripheral tree
	init_peripheral_tree();

	// user init section
	bsp_init();

	// take over `main loop`
	bsp_loop();
}


void bsp_init()
{}

void bsp_loop()
{}

void bsp_setup_peripheral()
{}

// ’‚¿Ô≤‚ ‘”√
gmp_peripheral_t gmp_iic_test_mem;
// This function is generated by bsp_c1 automatically.
void init_peripheral_tree()
{
	gmp_peripheral_t tmp_dev = GMP_IIC_1;
	// TODO check capacity
	gmp_iic1_hdev = &gmp_iic_test_mem;
	memcpy(gmp_iic1_hdev, &tmp_dev,sizeof(gmp_peripheral_t));
	// TODO implement extensions

}
