//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.

#include "prototypes.h"

#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

extern gmp_peripheral_t* gmp_iic1_hdev; // gmp_<peripheral_name>_hdev
#define GMP_IIC_1 {PROTO_PERIPHERAL_IIC, 10, &hi2c1, 0,0,0,0,0,0,0,0}

#define GMP_IIC_BH1750 {gmp_iic_dev_handle, 0x5F}


// functions
void init_peripheral_tree();
void bsp_setup_peripheral();
void bsp_loop();
void bsp_init();

#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_