// This file should be generated by `tools/bsp_c1`.
#ifndef GENERAL_MOTOR_PLAT


// GMP library version definition
#define GENERAL_MOTOR_PLAT
#define GMP_SERIAL_NUM     ((000000))

// GMP support chip select
#define MASTERCHIP STM32G030xx

// GMP Board select
#define MASTER_CHIP_SET NULL

// GMP C++ support
//#define GMP_CPLUSPLUS_ENABLE

// Compiler options
#define COMPILER_AC6

//////////////////////////////////////////////////////////////////////////
// GMP module config 

// Memory Management Deposit
// GMP/core/mm
#define GMP_MEMORY_MANAGEMENT

// Device and Peripheral Management Deposit
// GMP/core/dev
#define GMP_PERIPHERAL_IO

// Work flow Management Deposit
// GMP/core/workflow


//////////////////////////////////////////////////////////////////////////
// GMP extension config

#endif // GENERAL_MOTOR_PLAT
