/**
 * @file erro_code.show.inl
 * @author Javnson (javnson@zju.edu.cn)
 * @brief 
 * @version 0.1
 * @date 2024-09-30
 * 
 * @copyright Copyright GMP(c) 2024
 * 
 */

// This file is generated by `tools/error_code_gen` automatically.
// Please DO NOT change this file.

gmp_stat_t gmp_std_return(gmp_stat_t error_code)
{


	return error_code;
}

