/**
 * @file user_main.hpp
 * @author Javnson (javnson@zju.edu.cn)
 * @brief 
 * @version 0.1
 * @date 2024-09-30
 * 
 * @copyright Copyright GMP(c) 2024
 * 
 */

//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.


#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

	//////////////////////////////////////////////////////////////////////////
	// Handle Type definition, copy from <main.c>
	// 
	// 
	
#ifndef SPECIFY_PC_TEST_ENV



#endif // SPECIFY_PC_TEST_ENV


	//////////////////////////////////////////////////////////////////////////
	// Peripheral Variables
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
// This is the default debug device handle
extern dbgptr_gt default_debug_dev;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC



	//////////////////////////////////////////////////////////////////////////
	// Devices on the peripheral


	//////////////////////////////////////////////////////////////////////////
	// function


	// User should implement this two functions at least
	void user_init(void);
	void user_loop(void);

	//////////////////////////////////////////////////////////////////////////
	// Additionally functions



#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_
