//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.


//// standard typedef
//#include <core/gmp_core.hpp>



#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

	//////////////////////////////////////////////////////////////////////////
	// Handle Type definition, copy from <main.c>
extern	CAN_HandleTypeDef hcan;

extern	CRC_HandleTypeDef hcrc;

extern	I2C_HandleTypeDef hi2c1;

extern	SPI_HandleTypeDef hspi1;

extern	UART_HandleTypeDef huart1;
extern	UART_HandleTypeDef huart2;




	//////////////////////////////////////////////////////////////////////////
	// Peripheral Variables
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
// This is the default debug device handle
extern gmp_concept_write_direct* default_debug_dev;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC

extern gmp_iic_stm32_impl_t iic;
extern gmp_uart_stm32_impl_t dbg_uart;

	//////////////////////////////////////////////////////////////////////////
	// Devices on the peripheral
//	extern dac8563 da(&spi, &da_clr, &da_load, &da_sync);

	//////////////////////////////////////////////////////////////////////////
	// GMP PWM module config
	// PWM channel default flag

#define GMP_PWM_CHN_1 TIM_CHANNEL_1
#define GMP_PWM_CHN_2 TIM_CHANNEL_2
#define GMP_PWM_CHN_3 TIM_CHANNEL_3
#define GMP_PWM_CHN_4 TIM_CHANNEL_4
#define GMP_PWM_CHN_5 TIM_CHANNEL_5
#define GMP_PWM_CHN_6 TIM_CHANNEL_6
#define GMP_PWM_PERIPHERAL_HANDLE_TYPE TIM_HandleTypeDef*
#define gmp_write_pwm_cmp(_dev_, _channel_, _cmp_) __HAL_TIM_SET_COMPARE((TIM_HandleTypeDef*)_dev_, _channel_, _cmp_)
#define gmp_write_pwm_div(_dev_, _div_) __HAL_TIM_SET_AUTORELOAD((TIM_HandleTypeDef*)_dev_, _div_)


	//////////////////////////////////////////////////////////////////////////
	// function


	// User should implement this two functions at least
	void user_init(void);
	void user_loop(void);

	//////////////////////////////////////////////////////////////////////////
	// Additionally functions



#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_
