//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.


// standard typedef
#include <core/std/typedef.h>

#include <csp/chip_support_selection.h>

#include <core/dev/prototypes.h>

#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

	//////////////////////////////////////////////////////////////////////////
	// Handle Type definition

	extern ADC_HandleTypeDef hadc1;
	extern DMA_HandleTypeDef hdma_adc1;
	extern I2C_HandleTypeDef hi2c1;
	extern I2C_HandleTypeDef hi2c2;
	extern RTC_HandleTypeDef hrtc;
	extern SPI_HandleTypeDef hspi2;
	extern UART_HandleTypeDef huart1;
	extern UART_HandleTypeDef huart2;


	//////////////////////////////////////////////////////////////////////////
	// Peripheral Variables
	extern gmp_peripheral_t gmp_iic1; // gmp_<peripheral_name>_hdev
	extern gmp_iic_mapping_t gmp_iic_bh1750;
	extern gmp_iic_mapping_t gmp_iic_bmp180;

	extern gmp_peripheral_t gmp_uart_dbg;
	extern gmp_phy_mapping_t gmp_uart_dbg_port;

	//////////////////////////////////////////////////////////////////////////
	// Debug ports
	
	// default debug print device handle
	// This pointer should be redirect by <user/peripheral_mapping.c>
	// the debug_print is disabled until you set the pointer
	extern gmp_concept_write_direct* default_debug_dev;

	//////////////////////////////////////////////////////////////////////////
	// Peripheral Macros
#define GMP_IIC_1 {PROTO_PERIPHERAL_IIC, 10, &hi2c2,      \
	gmp_port_i2c_rx, gmp_port_i2c_tx,                       \
	NULL, NULL, 0, 0}

#define GMP_UART_DBG {PROTO_PERIPHERAL_UART, 20, &huart1, \
	gmp_port_uart_rx, gmp_port_uart_tx,                     \
	gmp_recv_int_string_default, NULL, 0, 0}

	//////////////////////////////////////////////////////////////////////////
	// Peripheral Mappings
#define GMP_IIC_BH1750 {&gmp_iic1, 0b0100011}
#define GMP_IIC_BMP180 {&gmp_iic1, 0b1110111}
#define GMP_UART_DBG_PORT {&gmp_uart_dbg}


	//////////////////////////////////////////////////////////////////////////
	// heap memory space
	extern uint8_t test_mem[1024];

	//////////////////////////////////////////////////////////////////////////
	// function
#ifdef __cplusplus
	extern "C"
	{
#endif

		// User should implement this two functions 
		void user_init(void);
		void user_loop(void);


#ifdef __cplusplus
	}
#endif

#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_
