// This file should be generated by `tools/bsp_c1`.
#ifndef GENERAL_MOTOR_PLAT


// GMP library version definition
#define GENERAL_MOTOR_PLAT
#define GMP_SERIAL_NUM     ((000000))

// GMP support chip select
#define MASTERCHIP TMS320F2806x

// GMP Board select
#define MASTER_CHIP_SET NULL

// GMP C++ support
//#define GMP_CPLUSPLUS_ENABLE

// Compiler options
//#define COMPILER_AC6

// Setup debug print 
#define GMP_DBG_PTR

//////////////////////////////////////////////////////////////////////////
// GMP module config 

// Memory Management Deposit
// GMP/core/mm
#define GMP_MEMORY_MANAGEMENT
//#define GMP_DEFAULT_MEMORY_MANUALLY // init and define default heap controller manually.
#define GMP_DEFAULT_HEAP_SIZE ((1536))

// Device and Peripheral Management Deposit
// GMP/core/dev
#define GMP_PERIPHERAL_IO

// Work flow Management Deposit
// GMP/core/workflow


//////////////////////////////////////////////////////////////////////////
// GMP CTL(Controller Template Library)

// Enable GMP CTL module
#define SPECIFY_ENABLE_GMP_CTL

// The rest of GMP CTL config please complete in <ctrl_config.h>

#endif // GENERAL_MOTOR_PLAT
