/**
 * @file peripheral_mapping.cpp
 * @author Javnson (javnson@zju.edu.cn)
 * @brief 
 * @version 0.1
 * @date 2024-09-30
 * 
 * @copyright Copyright GMP(c) 2024
 * 
 */
 
// This file's framework is generated by bsp_c1
#include <core/gmp_core.hpp>
#include <ctl/ctl.config.h>


void gmp_setup_peripheral()
{

}

void gmp_init_peripheral_tree()
{

}


void MainISR(void)
{
    // Get ADC result
#ifdef USING_SIMULINK_UDP_SIMULATE
    if (periodic_recv_routine(&udp_svr_obj) == 1)
    {
        exit(1);
    }
#endif // USING_SIMULINK_UDP_SIMULATE

    // Call GMP CTL
    ctl_dispatch();

    // write back PWM result
#ifdef USING_SIMULINK_UDP_SIMULATE
    if (periodic_transmit_routine(&udp_svr_obj) == 1)
    {
        exit(1);
    }
#endif // USING_SIMULINK_UDP_SIMULATE

}