/**
 * @file peripheral_mapping.cpp
 * @author Javnson (javnson@zju.edu.cn)
 * @brief 
 * @version 0.1
 * @date 2024-09-30
 * 
 * @copyright Copyright GMP(c) 2024
 * 
 */


// This file's framework is generated by bsp_c1
#include <gmp_core.hpp>
#include <ctl/ctl.config.h>


void setup_peripheral()
{

}

