
#ifndef _FILE_CTL_NANO_FRAMEWORK_SETTING_H_
#define _FILE_CTL_NANO_FRAMEWORK_SETTING_H_

// Enable GMP CTL Controller Framework Nano
 #ifndef SPECIFY_ENABLE_CTL_FRAMEWORK_NANO
 #define SPECIFY_ENABLE_CTL_FRAMEWORK_NANO
 #endif // SPECIFY_ENABLE_CTL_FRAMEWORK_NANO

#endif // _FILE_CTL_NANO_FRAMEWORK_SETTING_H_

