

// This file's framework is generated by bsp_c1
#include <core/gmp_core.hpp>
#include <ctl/ctrl_config.h>



//////////////////////////////////////////////////////////////////////////
// Peripherals implement classes
//gmp_uart_stm32_impl_t dbg_uart(&huart1);


//////////////////////////////////////////////////////////////////////////
// Devices on the peripheral

void gmp_setup_peripheral()
{

}

// This function should be implement by bsp_c1
void gmp_init_peripheral_tree()
{
	// enable debug port
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
//	default_debug_dev = &dbg_uart;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC


}

//////////////////////////////////////////////////////////////////////////
// interrupt reaction



