//////////////////////////////////////////////////////////////////////////
// THIS FILE SHOULD NOT CHANGE.
// This file is generated by bsp_c1 tool.


#ifndef _FILE_PERIPHERAL_MAPPING_H_
#define _FILE_PERIPHERAL_MAPPING_H_

#ifdef __cplusplus
extern "C"
{
#endif

	//////////////////////////////////////////////////////////////////////////
	// Handle Type definition, copy from <main.c>
//extern	CAN_HandleTypeDef hcan;

//extern	CRC_HandleTypeDef hcrc;

//extern	I2C_HandleTypeDef hi2c1;

//extern	SPI_HandleTypeDef hspi1;

//extern	UART_HandleTypeDef huart1;
//extern	UART_HandleTypeDef huart2;

//extern TIM_HandleTypeDef htim1;



	//////////////////////////////////////////////////////////////////////////
	// Peripheral Variables
#if defined SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC
// This is the default debug device handle
extern gmp_concept_write_direct* default_debug_dev;
#endif // SPECIFY_ENABLE_DEFUALT_DEBUG_PRINT_FUNC

//extern gmp_iic_stm32_impl_t iic;
//extern gmp_uart_stm32_impl_t dbg_uart;
//extern gmp_pwm1ch_stm32_impl_t pwm_ch1;

	//////////////////////////////////////////////////////////////////////////
	// Devices on the peripheral


	//////////////////////////////////////////////////////////////////////////
	// function


	// User should implement this two functions at least
	void user_init(void);
	void user_loop(void);

	//////////////////////////////////////////////////////////////////////////
	// Additionally functions



#ifdef __cplusplus
}
#endif

#endif // _FILE_PERIPHERAL_MAPPING_H_
